### PR TITLE
fix utf-8 encoding bug

### PR DESCRIPTION
**Pull request by esfahanweb**
Hi,

I found a little bug when creating UTF-8 menus and fixed it.

best regards

### CODE REVIEW

**Comment by jchristopher** [comment]
Thank you!

Can you please outline specifically what the bug is, how to reproduce it, and what this PR does to resolve the issue?

Also it looks like there are many changes that edit the code formatting only, so I'm not sure which changes are related to the fix. If you could resubmit the PR with only the lines that directly affect the bug that would be great, thank you again!

**Comment by esfahanweb** [comment]
Hi,

if you save WP menus with Persian title you will get the incorrect title in frontend duo to `loadHTML` without UTF-8 converting

I just change this line
```php
$dom->loadHTML($nav_menu);
```
to this
```php
$dom->loadHTML(mb_convert_encoding($nav_menu, 'HTML-ENTITIES', 'UTF-8'));
```

other changes are the IDE PHP code auto-format

**Comment by esfahanweb** [comment]
Did you check it?

**Comment by jchristopher** [comment]
Fixed in https://github.com/jchristopher/searchwp-modal-search-form/commit/2918ed59d9628ad5a3a635652c426bba6e15a6b7

**Pull request closed without merging**
